# Generated by Django 2.2.24 on 2021-07-28 10:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20210727_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=cloudinary.models.CloudinaryField(default='pdf', max_length=255, verbose_name='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='book_app.Profile'),
            preserve_default=False,
        ),
    ]
