# Generated by Django 2.2.24 on 2021-07-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20210728_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='bookapp/pdfs/'),
        ),
    ]
