# Generated by Django 2.2.24 on 2021-07-28 15:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_auto_20210728_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='PDF'),
        ),
    ]
