# Generated by Django 2.2.24 on 2021-07-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='bookapp/pdfs/'),
        ),
    ]
