# Generated by Django 2.2.24 on 2021-07-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_auto_20210729_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='content',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='design',
            new_name='entertainment',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='usability',
            new_name='plot',
        ),
    ]
